name: Clean Docker Image

description: Clean Docker Image

author: "Grinch27"

runs:
  using: composite
  steps:
    - name: Clean Docker Image
      shell: bash
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        df -Th

        docker image list
        docker image prune -a -f
        # for image in $(docker images -q); do
        #   docker rmi -f $image
        # done

        df -Th
