name: Setup Disk

description: Setup Disk

author: "Grinch27"

inputs:
  path_build:
    description: Mount point to use
    required: true
  root_num:
    description: Reserved GiB on /
    required: false
    default: "4"
  mnt_num:
    description: Reserved GiB on /mnt
    required: false
    default: "1"

runs:
  using: composite
  steps:
    - name: Setup Disk
      shell: bash
      working-directory: /
      env:
        path_build: ${{ inputs.path_build }}
        root_num: ${{ inputs.root_num }}
        mnt_num: ${{ inputs.mnt_num }}
      run: |
        echo "Current working directory: $(pwd)"
        df -Th

        # 获取 /mnt 和 / 分区的剩余空间
        mnt_available=$(df -B1 /mnt | tail -1 | awk '{print $4}')
        root_available=$(df -B1 / | tail -1 | awk '{print $4}')
        echo "Raw available space in /mnt (bytes): ${mnt_available}"
        echo "Raw available space in / (bytes): ${root_available}"

        # 减去缓冲空间：/mnt 和 / 分区分别减去缓冲
        gb2bytes=$((1024 * 1024 * 1024))
        mnt_size=$((${mnt_available} - ${{ env.mnt_num }} * ${gb2bytes}))
        root_size=$((${root_available} - ${{ env.root_num }} * ${gb2bytes}))
        echo "Available space in /mnt (bytes): ${mnt_size}"
        echo "Available space in / (bytes): ${root_size}"

        # 创建磁盘映像文件
        sudo truncate -s "${mnt_size}" /mnt/mnt.img
        sudo truncate -s "${root_size}" /root.img

        # 动态分配可用的循环设备
        LOOP_MNT=$(sudo losetup --find --show /mnt/mnt.img)
        LOOP_ROOT=$(sudo losetup --find --show /root.img)
        echo "Assigned loop device for /mnt/mnt.img: ${LOOP_MNT}"
        echo "Assigned loop device for /root.img: ${LOOP_ROOT}"

        # 创建物理卷
        sudo pvcreate "${LOOP_MNT}"
        sudo pvcreate "${LOOP_ROOT}"
        # 创建卷组
        sudo vgcreate github "${LOOP_MNT}" "${LOOP_ROOT}"

        # 在 github 卷组上创建一个名为 runner 的逻辑卷，使用所有可用空间, 并格式化为XFS文件系统
        sudo lvcreate -n runner -l 100%FREE github
        sudo mkfs.xfs /dev/github/runner

        # 创建一个挂载点 ${path_build}, 将 runner 逻辑卷挂载到 ${path_build}, 将 ${path_build} 的所有者和组更改为 runner
        sudo mkdir -p "${path_build}"
        sudo mount /dev/github/runner "${path_build}"
        sudo chown -R runner:runner "${path_build}"

        df -Th
