name: Clean Runner

description: Clean Runner

author: "Grinch27"

runs:
  using: composite
  steps:
    - name: Clean Runner
      shell: bash
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        df -Th
        sudo -E apt-get -yqq update
        package_installed=$(dpkg-query -W -f='${binary:Package}\n')

        # ===== Clean Apt =====
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md

        # ----- package for purge -----
        packages_purge=(
          "docker*"
          "ghc*"
          "zulu*"
          "google*"
          "firefox*"
          "dotnet*"
          "powershell*"
          "microsoft-edge*"
          "sqlite*"
          "postgresql*"
          "mysql*"
          "mongodb*"
          "moby*"
          "apache2*"
          "nginx*"
          "php*"
        )
        sudo -E apt-get -yqq autoremove --purge "${packages_purge[@]}"

        # ===== Clean Browsers and Drivers =====
        sudo -E rm -rf /usr/local/share/chromedriver-linux64
        sudo -E rm -rf /usr/local/share/chromium
        sudo -E rm -rf /usr/local/share/edge_driver
        sudo -E rm -rf /usr/local/share/gecko_driver
        sudo -E rm -rf /usr/share/java/selenium-server.jar

        # ===== Clean PowerShell Tools =====
        sudo -E rm -rf /usr/local/share/powershell

        # ===== Clean AGENT_TOOLSDIRECTORY =====
        # 如果环境变量 AGENT_TOOLSDIRECTORY 不为空，则删除该目录及其所有内容
        [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"

        # ===== Clean Swap =====
        # 关闭所有交换空间 删除指定的交换文件
        sudo swapoff -a
        sudo rm -f /swapfile /mnt/swapfile

        # ========== reload ==========
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E systemctl daemon-reload
        df -Th
