name: Environment for GH Actions in Docker

# https://docs.github.com/zh/actions/reference/workflows-and-actions/metadata-syntax#runs-for-composite-actions

description: Environment for GH Actions in Docker

author: "Grinch27"

runs:
  using: composite
  steps:
    - name: Load Custom Environment Variables
      id: env-custom
      uses: Grinch27/github-actions/.github/actions/input-custom@main

    - name: (Apt) Docker Needed for Actions
      id: fix-docker
      uses: Grinch27/github-actions/.github/actions/fix-indocker@main

    - name: (Apt) install packages - OpenWrt
      id: apt-openwrt
      uses: Grinch27/github-actions/.github/actions/apt-openwrt@main
    # ========== General Environment Setup: Start ==========
    - name: (Env) Environment for Toolchain
      id: env-toolchain
      uses: Grinch27/github-actions/.github/actions/env-toolchain@main
      with:
        # ----- gcc -----
        gcc_purge: ${{ env.gcc_purge }}
        gcc_install: ${{ env.gcc_install }}
        gcc_switch: ${{ env.gcc_switch }}
        gcc_version: ${{ env.gcc_version }}
        gcc_aarch64: ${{ env.gcc_aarch64 }}
        # ----- clang -----
        clang_purge: ${{ env.clang_purge }}
        clang_install: ${{ env.clang_install }}
        clang_switch: ${{ env.clang_switch }}
        clang_version: ${{ env.clang_version }}
        # ----- jdk -----
        jdk_purge: ${{ env.jdk_purge }}
        jdk_install: ${{ env.jdk_install }}
        jdk_switch: ${{ env.jdk_switch }}
        jdk_version: ${{ env.jdk_version }}
        # ----- docker -----
        docker_install: ${{ env.docker_install }}
        qemu_install: ${{ env.qemu_install }}

    # ========== General Environment Setup: End ==========
    - name: (Disk) disk workspace
      id: disk
      uses: Grinch27/github-actions/.github/actions/setup-disk@main
      with:
        path_build: ${{ env.PATH_build }}
        root_num: 4
        mnt_num: 1
