name: Environment for GH Actions in Docker

# https://docs.github.com/zh/actions/reference/workflows-and-actions/metadata-syntax#runs-for-composite-actions

description: Environment for GH Actions in Docker

author: "Grinch27"

inputs:
  # ----- gcc -----
  gcc_purge:
    description: "gcc_purge"
    required: false
    default: "false"
  gcc_install:
    description: "gcc_install"
    required: false
    default: "false"
  gcc_switch:
    description: "gcc_switch"
    required: false
    default: "false"
  gcc_version:
    description: "gcc_version"
    required: false
    default: ""
  gcc_aarch64:
    description: "gcc_aarch64"
    required: false
    default: "false"
  # ----- clang -----
  clang_purge:
    description: "clang_purge"
    required: false
    default: "false"
  clang_install:
    description: "clang_install"
    required: false
    default: "false"
  clang_switch:
    description: "clang_switch"
    required: false
    default: "false"
  clang_version:
    description: "clang_version"
    required: false
    default: ""
  # ----- jdk -----
  jdk_purge:
    description: "jdk_purge"
    required: false
    default: "false"
  jdk_install:
    description: "jdk_install"
    required: false
    default: "false"
  jdk_switch:
    description: "jdk_switch"
    required: false
    default: "false"
  jdk_version:
    description: "jdk_version"
    required: false
    default: ""
  # ----- docker -----
  docker_install:
    description: "docker_install"
    required: false
    default: "false"
  qemu_install:
    description: "qemu_install"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    # ========== General Environment Setup: Start ==========
    - name: (Env) Environment for Toolchain
      id: env-toolchain
      uses: Grinch27/github-actions/.github/actions/env-toolchain@main
      with:
        # ----- gcc -----
        gcc_purge: ${{ env.gcc_purge }}
        gcc_install: ${{ env.gcc_install }}
        gcc_switch: ${{ env.gcc_switch }}
        gcc_version: ${{ env.gcc_version }}
        gcc_aarch64: ${{ env.gcc_aarch64 }}
        # ----- clang -----
        clang_purge: ${{ env.clang_purge }}
        clang_install: ${{ env.clang_install }}
        clang_switch: ${{ env.clang_switch }}
        clang_version: ${{ env.clang_version }}
        # ----- jdk -----
        jdk_purge: ${{ env.jdk_purge }}
        jdk_install: ${{ env.jdk_install }}
        jdk_switch: ${{ env.jdk_switch }}
        jdk_version: ${{ env.jdk_version }}
        # ----- docker -----
        docker_install: ${{ env.docker_install }}
        qemu_install: ${{ env.qemu_install }}

    # ========== General Environment Setup: End ==========
