name: Git Revision Info

# https://docs.github.com/zh/actions/reference/workflows-and-actions/metadata-syntax#runs-for-composite-actions

description: Git Revision Info

author: "Grinch27"

inputs:
  path_target:
    description: "Path to the git repository"
    required: false
    default: "."

outputs:
  tag_release:
    description: "tag_release"
    value: ${{ steps.git-rev.outputs.tag_release }}

runs:
  using: composite
  steps:
    - name: (Git) Git Revision Info
      id: git-rev
      shell: bash
      working-directory: ${{ inputs.path_target }}
      run: |
        echo -e "Current working directory: $(pwd)"
        set -x

        # ----- git describe --all --long -> refs/heads/master-0-gf5b6b6d -----
        desc_long=$(git describe --all --long | cut -d'/' -f2-)
        echo "desc_long=${desc_long}"

        # ----- branch: git rev-parse --abbrev-ref HEAD -> master -----
        rev_ref=$(git rev-parse --abbrev-ref HEAD)
        echo "rev_ref=${rev_ref}"

        # ----- full hash: git rev-parse HEAD -----
        rev_hash=$(git rev-parse HEAD)
        echo "rev_hash=${rev_hash}"

        # ----- short hash: git rev-parse --short HEAD -> f5b6b6d -----
        rev_short=$(git rev-parse --short HEAD)
        echo "rev_short=${rev_short}"

        # ----- commit count: git rev-list --count HEAD -> 1000 ----- !!! work without --depth=1
        rev_count=$(git rev-list --count HEAD)
        echo "rev_count=${rev_count}"

        # ----- DIY -----
        tag_release="${rev_ref}-${rev_count}-${rev_short}"
        git_desc="${rev_ref}-${rev_count}-${rev_short}"

        # ----- outputs -----
        echo "tag_release=${tag_release}" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
        echo "git_desc=${git_desc}" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
