name: Purge Snap

description: Purge snapd and related data from the runner

author: "Grinch27"

runs:
  using: composite
  steps:
    - name: Purge Snap
      shell: bash
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        df -Th

        sudo -E apt-get -yqq update
        package_installed=$(dpkg-query -W -f='${binary:Package}\n')

        if command -v snap >/dev/null 2>&1; then
          sudo snap list || true
          for p in $(snap list | awk 'NR>1 {print $1}'); do
            sudo snap remove "$p"
          done
          sudo systemctl stop snapd || true
          sudo systemctl disable --now snapd.socket || true
          sudo apt-get -yqq autoremove --purge snapd || true
        fi

        sudo rm -rf ~/snap
        sudo rm -rf /snap
        sudo rm -rf /var/snap
        sudo rm -rf /var/lib/snapd
        sudo rm -rf /var/cache/snapd

        sudo bash -c 'cat <<EOF > /etc/apt/preferences.d/nosnap.pref
        Package: snapd
        Pin: release a=*
        Pin-Priority: -10
        EOF'

        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E systemctl daemon-reload
        df -Th
