name: Switch GCC AArch64

description: Switch GCC AArch64

author: "Grinch27"

inputs:
  gcc_version:
    description: "Version"
    required: false
    default: "14"

runs:
  using: composite
  steps:
    - name: Switch GCC AArch64
      shell: bash
      working-directory: /
      env:
        gcc_version: ${{ inputs.gcc_version }}
      run: |
        echo -e "Current working directory: $(pwd)"
        df -Th
        sudo -E apt-get -yqq update
        package_installed=$(dpkg-query -W -f='${binary:Package}\n')

        packages_install=(
          "gcc-${{ env.gcc_version }}-aarch64-linux-gnu"
          "cpp-${{ env.gcc_version }}-aarch64-linux-gnu"
        )
        sudo -E apt-get -yqq install "${packages_install[@]}"

        # AArch64专用设置，涵盖所有带版本号的aarch64-linux-gnu工具
        ls /usr/bin/aarch64-linux-gnu-*
        tools_aarch64=(
          "aarch64-linux-gnu-gcc"
          "aarch64-linux-gnu-cpp"
          "aarch64-linux-gnu-gcc-ar"
          "aarch64-linux-gnu-gcc-nm"
          "aarch64-linux-gnu-gcc-ranlib"
          "aarch64-linux-gnu-gcov"
          "aarch64-linux-gnu-gcov-dump"
          "aarch64-linux-gnu-gcov-tool"
          "aarch64-linux-gnu-lto-dump"
        )
        for tool in "${tools_aarch64[@]}"; do
          versions=$(ls /usr/bin/${tool}-* 2>/dev/null | grep -Eo '[0-9]+$' | sort -u)
          for version in ${versions}; do
            sudo update-alternatives --install /usr/bin/${tool} ${tool} /usr/bin/${tool}-${version} ${version}
          done
        done
        sudo update-alternatives --query aarch64-linux-gnu-gcc
        # 切换到所需版本
        for tool in "${tools_aarch64[@]}"; do
          sudo update-alternatives --set ${tool} /usr/bin/${tool}-${{ env.gcc_version }}
        done

        # ========== reload ==========
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E systemctl daemon-reload
        df -Th

        # 验证版本
        aarch64-linux-gnu-gcc --version
        echo "Switched to AArch64 GCC version: ${{ env.gcc_version }}"
