name: Switch GCC AArch64

description: Switch GCC AArch64

author: "Grinch27"

inputs:
  gcc_version:
    description: "Version"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: (Vars) Resolve GCC suffix
      id: gcc-vars
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
        gcc_version: ${{ inputs.gcc_version }}
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        df -Th
        sudo -E apt-get -yqq update
        package_installed=$(dpkg-query -W -f='${binary:Package}\n')

        if [ -n "${{ env.gcc_version }}" ]; then
          pkg_suffix="-${{ env.gcc_version }}"
          lib_version="${{ env.gcc_version }}"
        else
          pkg_suffix=""
          lib_version=""
        fi
        echo "pkg_suffix=$pkg_suffix" >> "$GITHUB_OUTPUT"
        echo "lib_version=$lib_version" >> "$GITHUB_OUTPUT"

    - name: Install GCC AArch64
      id: install-gcc-aarch64
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
        pkg_suffix: ${{ steps.gcc-vars.outputs.pkg_suffix }}
        lib_version: ${{ steps.gcc-vars.outputs.lib_version }}
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        df -Th
        sudo -E apt-get -yqq update
        package_installed=$(dpkg-query -W -f='${binary:Package}\n')

        packages_install=(
          "gcc${{ env.pkg_suffix }}-aarch64-linux-gnu"
          "cpp${{ env.pkg_suffix }}-aarch64-linux-gnu"
        )
        sudo -E apt-get -yqq install "${packages_install[@]}"

    - name: Configure AArch64 alternatives
      id: configure-aarch64-alternatives
      # if: ${{ steps.install-gcc-aarch64.outcome == 'success' }}
      if: ${{ inputs.gcc_version != '' }}
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
        pkg_suffix: ${{ steps.gcc-vars.outputs.pkg_suffix }}
        lib_version: ${{ steps.gcc-vars.outputs.lib_version }}
      working-directory: /
      run: |
        # AArch64专用设置，涵盖所有带版本号的aarch64-linux-gnu工具
        ls /usr/bin/aarch64-linux-gnu-*
        tools_aarch64=(
          "aarch64-linux-gnu-gcc"
          "aarch64-linux-gnu-cpp"
          "aarch64-linux-gnu-gcc-ar"
          "aarch64-linux-gnu-gcc-nm"
          "aarch64-linux-gnu-gcc-ranlib"
          "aarch64-linux-gnu-gcov"
          "aarch64-linux-gnu-gcov-dump"
          "aarch64-linux-gnu-gcov-tool"
          "aarch64-linux-gnu-lto-dump"
        )
        for tool in "${tools_aarch64[@]}"; do
          versions=$(ls /usr/bin/${tool}-* 2>/dev/null | grep -Eo '[0-9]+$' | sort -u)
          for version in ${versions}; do
            sudo update-alternatives --install /usr/bin/${tool} ${tool} /usr/bin/${tool}-${version} ${version}
          done
        done
        sudo update-alternatives --query aarch64-linux-gnu-gcc
        # 切换到所需版本
        for tool in "${tools_aarch64[@]}"; do
          sudo update-alternatives --set ${tool} /usr/bin/${tool}-${{ env.lib_version }}
        done

    - name: (Apt) Reload
      id: apt-reload
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E systemctl daemon-reload
        df -Th

    - name: Verify AArch64 GCC
      id: verify-aarch64-gcc
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        df -Th
        # 验证版本
        aarch64-linux-gnu-gcc --version
        echo "Switched to AArch64 GCC version: ${{ env.gcc_version }}"
