name: Apt OpenWrt

description: Apt OpenWrt

author: "Grinch27"

runs:
  using: composite
  steps:
    - name: Apt OpenWrt
      shell: bash
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        df -Th

        sudo -E apt-get -yqq update
        package_installed=$(dpkg-query -W -f='${binary:Package}\n')

        packages_install=(
          "ack"
          "antlr3"
          "asciidoc"
          "autoconf"
          "automake"
          "autopoint"
          "bc"
          "binutils"
          "bison"
          "build-essential"
          "bzip2"
          "ca-certificates"
          # "clang"
          # "clangd"
          "cmake"
          "cpio"
          "curl"
          "device-tree-compiler"
          "dwarves"
          "ecj"
          "fastjar"
          "flex"
          "gawk"
          # "g++"
          # "gcc"
          # "gcc-aarch64-linux-gnu"
          "git"
          "git-lfs"
          "gnupg"
          "gperf"
          "haveged"
          "help2man"
          "intltool"
          "jq"
          "libelf-dev"
          "libglib2.0-dev"
          "libgmp3-dev"
          "libltdl-dev"
          "libmpc-dev"
          "libmpfr-dev"
          "libncurses5-dev"
          "libreadline-dev"
          "libssl-dev"
          "libtool"
          "libxml2"
          "libxml2-utils"
          "lld"
          "lldb"
          "lz4"
          "lzop"
          "make"
          "mkisofs"
          "ninja-build"
          "p7zip-full"
          "patch"
          "pkgconf"
          "python3"
          "python3-pip"
          "re2c"
          "rsync"
          "schedtool"
          "scons"
          "squashfs-tools"
          "subversion"
          "swig"
          "uglifyjs"
          "unzip"
          "vim"
          "wget"
          "xsltproc"
          "zip"
          "zlib1g-dev"
          # "usign"
        )
        sudo -E apt-get -yqq install "${packages_install[@]}"

        # ========== reload ==========
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E systemctl daemon-reload
        df -Th
