name: Setup GCC

description: Setup GCC

author: "Grinch27"

inputs:
  gcc_version:
    description: "GCC version"
    required: false
    default: "14"
  gcc_toggle:
    description: "Toggle for GCC"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: (Toggle) Ubuntu devel for GCC
      if: ${{ inputs.gcc_toggle == 'devel' }}
      shell: bash
      working-directory: /
      run: |
        # sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ devel main restricted universe multiverse" || true
        # sudo apt update

        echo "deb http://archive.ubuntu.com/ubuntu/ devel main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/devel.list
        sudo -E apt-get -yqq update

        if [ -L /lib32 ] && [ ! -e /lib32 ]; then
          echo "Fixing dangling /lib32 symlink"
          sudo rm /lib32
          sudo mkdir -p /lib32
        fi

    - name: (Toggle) PPA for GCC
      if: ${{ inputs.gcc_toggle == 'ppa' }}
      shell: bash
      working-directory: /
      run: |
        # https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/ppa || true
        sudo -E apt-get -yqq update

    - name: Setup GCC
      shell: bash
      working-directory: /
      env:
        gcc_version: ${{ inputs.gcc_version }}
      run: |
        echo "Current working directory: $(pwd)"
        df -Th

        packages_install=(
          # ----- gcc -----
          "gcc-${gcc_version}"
          "libgcc-${gcc_version}-dev"
          "gcc-${gcc_version}-multilib"
          # ----- g++ -----
          "g++-${gcc_version}"
          "libstdc++-${gcc_version}-dev"
          "g++-${gcc_version}-multilib"
          # ----- cpp -----
          "cpp-${gcc_version}"
          # ----- gfortran -----
          "gfortran-${gcc_version}"
          "libgfortran-${gcc_version}-dev"
        )
        echo "Packages to be installed: ${packages_install[@]}"
        sudo -E apt-get -yqq install "${packages_install[@]}"

        # ========== reload ==========
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E systemctl daemon-reload
        df -Th

    - name: (Remove) Ubuntu devel for GCC
      if: ${{ inputs.gcc_toggle == 'devel' }}
      shell: bash
      working-directory: /
      run: |
        sudo rm /etc/apt/sources.list.d/devel.list
        sudo -E apt-get -yqq update

    - name: (Remove) PPA for GCC
      if: ${{ inputs.gcc_toggle == 'ppa' }}
      shell: bash
      working-directory: /
      run: |
        sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/ppa || true
        sudo -E apt-get -yqq update
