name: Switch Clang

description: Switch Clang

author: "Grinch27"

inputs:
  clang_version:
    description: "Version"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: (Vars) Resolve suffix
      id: vars
      shell: bash
      working-directory: /
      env:
        clang_version: ${{ inputs.clang_version }}
      run: |
        if [ -n "${{ env.clang_version }}" ]; then
          pkg_suffix="-${{ env.clang_version }}"
          lib_version="${{ env.clang_version }}"
        else
          pkg_suffix=""
          lib_version=""
        fi
        echo "pkg_suffix=$pkg_suffix" >> "$GITHUB_OUTPUT"
        echo "lib_version=$lib_version" >> "$GITHUB_OUTPUT"

    - name: Configure alternatives
      id: alternatives
      if: ${{ inputs.clang_version != '' }}
      shell: bash
      working-directory: /
      env:
        pkg_suffix: ${{ steps.vars.outputs.pkg_suffix }}
        lib_version: ${{ steps.vars.outputs.lib_version }}
      run: |
        tools_clang=(
          "clang"
          "clang-format"
          "clang-tidy"
          "clangd"
          # "lld"
          # "lldb"
        )
        for tool in "${tools_clang[@]}"; do
          versions=$(ls /usr/bin/${tool}-* 2>/dev/null | grep -Eo '[0-9]+$' | sort -u || true)
          for version in ${versions}; do
            sudo update-alternatives --install /usr/bin/${tool} ${tool} /usr/bin/${tool}-${version} ${version}
          done
        done

        sudo update-alternatives --query clang    || true
        sudo update-alternatives --query clang-format || true
        sudo update-alternatives --query clang-tidy   || true

        for tool in "${tools_clang[@]}"; do
          sudo update-alternatives --set ${tool} /usr/bin/${tool}-${lib_version} || true
        done

    - name: (Apt) Reload
      id: apt-reload
      shell: bash
      working-directory: /
      run: |
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean
        sudo -E systemctl daemon-reload
        df -Th

    - name: Verify
      id: verify
      shell: bash
      working-directory: /
      env:
        clang_version: ${{ inputs.clang_version }}
      run: |
        clang --version || true
        clang-format --version || true
        clang-tidy --version || true
        echo "Switched to Clang version ${clang_version}"
