name: Check in Docker

description: Check whether current job runs inside Docker

author: "Grinch27"

outputs:
  in_container:
    description: Whether current job runs inside Docker
    value: ${{ steps.check-indocker.outputs.in_container }}

runs:
  using: composite
  steps:
    - name: Check in Docker
      id: check-indocker
      shell: bash
      working-directory: /
      run: |
        echo -e "Current working directory: $(pwd)"
        set -euo pipefail

        if [ -f /.dockerenv ]; then
          echo "in_container=true" | tee -a "${GITHUB_OUTPUT}"
        else
          echo "in_container=false" | tee -a "${GITHUB_OUTPUT}"
        fi

        env_vars=(
          "in_container"
        )
        for var in "${env_vars[@]}"; do
          echo "${var}=${!var}" | tee -a "$GITHUB_ENV"
        done
